
arrayinc: arrayinc.o #helper
	gcc -o arrayinc arrayinc.o
arrayinc.o: arrayinc.c
	gcc -O -Wall -c arrayinc.c
cleanarrayinc:
	rm -f arrayinc.o arrayinc
runarrayinc:
	./arrayinc

lab5q1: lab5q1.o #helper
	gcc -o lab5q1 lab5q1.o
lab5q1.o: lab5q1.c
	gcc -O -Wall -c lab5q1.c
cleanlab5q1:
	rm -f lab5q1.o lab5q1
runlab5q1:
	./lab5q1 testing